
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Random;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class VentanaBuscaminas extends javax.swing.JFrame {

    int filas = 20;
    int columnas = 30;
    
    Boton [][] arrayBotones = new Boton[filas][columnas];
    
    /**
     * Creates new form VentanaBuscaminas
     */
    public VentanaBuscaminas() {
        initComponents();
        setSize(1024,768);
        getContentPane().setLayout(new GridLayout(filas, columnas));
        for (int i=0; i<filas; i++){
            for(int j=0; j<columnas; j++){
                Boton boton = new Boton(i,j);
                boton.setBorder(null);
                getContentPane().add(boton);
                arrayBotones[i][j] = boton;
                boton.addMouseListener(new MouseAdapter(){
                    @Override
                    public void mousePressed(MouseEvent evt){
                        botonPulsado(evt);
                    }
                });
            }
        }
        ponMinas(30);
        cuentaMinas();
    }
    
    private void ponMinas (int numeroMinas){
        Random r = new Random();
        for(int i = 0; i < numeroMinas; i++) {
        int f = r.nextInt(filas);
        int c = r.nextInt(columnas);
  
        
        arrayBotones [f][c].setMina(1);
        arrayBotones [f][c].setText("M");
          }
    }
    
    //cuentaMinas es un método que apra cada boton calcula el numero
    //de minas que tiene alrededor  
    
    private void cuentaMinas(){
        int minas = 0 ;
          for (int i=0; i<filas; i++){
            for(int j=0; j<columnas; j++){
                if((i > 0) && (j > 0) && (i < filas-1) && j < columnas-1){
              //la mina de arriba a la izquierda
              minas =minas +  arrayBotones[i-1][j-1].getMina();
              minas =minas +  arrayBotones[i][j-1].getMina();
              minas =minas +  arrayBotones[i+1][j-1].getMina();
                
              minas =minas +  arrayBotones[i-1][j].getMina();
              minas =minas +  arrayBotones[i+1][j].getMina();             
              
              minas =minas +  arrayBotones[i-1][j+1].getMina();
              minas =minas +  arrayBotones[i][j+1].getMina();
              minas =minas +  arrayBotones[i+1][j+1].getMina();
                }
                arrayBotones[i][j].setNumeroMinasAlrededor(minas);
               if(arrayBotones[i][j].getMina() == 0){
                arrayBotones[i][j].setText(String.valueOf(minas));
                
               }
                
                 minas = 0;
            }
        }
    }
    
    private void botonPulsado (MouseEvent e){
        Boton miBoton = (Boton) e.getComponent();
        if(e.getButton() == MouseEvent.BUTTON3){
            miBoton.setText("?");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscaminas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscaminas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscaminas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscaminas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaBuscaminas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
